### ISSUE TITLE
Trying to cancel deconstruction of an entity not marked for deconstruction

### ISSUE THREAD

**Issue by mineblow** [NoxyNixie/Noxys_Multidirectional_Trains#10]
i have a crash report on factorio forums. https://forums.factorio.com/viewtopic.php?f=7&t=123296&p=648022#p648022 i believe i have pin point the crash to your mod causing it. there are saves located on the forums.

**Comment by mineblow** [comment]
factorio devs figured out it was a bug on there end

**Comment by NoxyNixie** [comment]
Thanks for relaying the info.
