### ISSUE TITLE
Train won't stop when set to manual

### ISSUE THREAD

**Issue by ChuckSavage** [NoxyNixie/Noxys_Multidirectional_Trains#4]
So, I posted this as a bug on the ([factorio forums](https://forums.factorio.com/59220)), and Rseding91 says its this mods fault. I'm attaching the save game and the mods I was using in setting up a demo to try and test the other issue I posted here. 

[cheats1.zip](https://github.com/CyaNox/Noxys_Multidirectional_Trains/files/1864626/cheats1.zip)
[mods.zip](https://github.com/CyaNox/Noxys_Multidirectional_Trains/files/1864627/mods.zip)

**Comment by NoxyNixie** [comment]
I don't think my mod stops you from changing the train state to manual mode. But I'll have a look at this when I'm back from vacation.

**Comment by ChuckSavage** [comment]
I'm a programmer, but not familiar with lua and modding, so this may not be it, but it seems to me it is. It resets the manual_mode of a train each time the event is run in control.lua, such that a rotated train can't go to manual, or so it seems.

```
if rotated then
				train.manual_mode = global.lastmode[id]
end
```

**Comment by NoxyNixie** [comment]
It does that but that should all happen in a single tick which means it reads the manual state then proceeds to set it all in one tick. You changing the trains state should not happen in between where it is read and where it is set (unless there is a logic path I missed which I will check when I'm back).

**Comment by ChuckSavage** [comment]
okay, you're right. I unzipped the mod folder (and moved the zip folder out of the mods folder) and commented out the line, and it had no effect. I'll keep looking.
`train.manual_mode = global.lastmode[id]`

**Comment by ChuckSavage** [comment]
Okay fixed it. The 2nd half of the if moving didn't check for `if not train.manual_mode`.

You may want to check it out before committing the following. I moved the `if not train.manual_mode` to the first line in the for loop, since nothing changes otherwise if manual_mode is true.

I forked your repo, and uploaded the fixed control.lua. Have a look at it here:

https://github.com/ChuckSavage/Noxys_Multidirectional_Trains/blob/master/control.lua


Though this doesn't unrotate a train, but when the train does move to a schedule location it does get unrotated.

**Comment by NoxyNixie** [comment]
Can you make it a pull request? (I just got back from vacation but am really tired from the 6 hour driving).

**Comment by ChuckSavage** [comment]
Done

**Comment by NoxyNixie** [comment]
Thanks and it looks like its not the behavior I want since a stopped train even in manual mode should still rotate its locomotives. With your patch it just ignores manual mode trains.

I'll probably have a stab at it tomorrow. See if I can find a completely different and better solution altogether.

**Comment by ChuckSavage** [comment]
I tried that too, but I didn't know enough about modding factorio to accomplish it.

I don't mind living with the quirk of having the un-rotated-back manual mode train(s), since setting it to go somewhere will fix it, since it is still in the global array.

**Comment by NoxyNixie** [comment]
Could you test this in version 0.0.5 and reopen if it still is not working correctly?

**Comment by ChuckSavage** [comment]
This seems to work fine. At least it isn't the behavior it was before.
