### ISSUE TITLE
Disabling mod doesn't unrotate rotated trains

### ISSUE THREAD

**Issue by ChuckSavage** [NoxyNixie/Noxys_Multidirectional_Trains#6]
As mentioned in another issue, I was going to disable the mod. Well, disabling didn't unrotate the trains with rotated locomotives.

**Comment by NoxyNixie** [comment]
A disabled mod can't "unrotate" or perform any actions when it is disabled unless a mod specifically adds a thing you can execute before disabling it.

I could probably implement something like that but it would take away from the time I can spend actually implementing things so this will have a very low priority or might even end up on the pile of "won't fix".

**Comment by ChuckSavage** [comment]
Before I came across this, I was thinking of a mod option that disabled the rotating of trains, that could be done in the mod's settings. I know it defeats the point of the mod, but that might be a solution. So if a person runs the mod for a little while longer with that option set, then the trains would eventually all be unrotated. 

There's probably no way currently to show number of trains in the rotated array is there?

**Comment by NoxyNixie** [comment]
I added an option to disable the mod through the mod settings. Once disabled in the mod settings it will immediately revert all rotated trains. You can then save and disable the mod after (though it won't actually do anything if you leave the mod enabled but the setting disabled).

In my limited testing this on its own caused trains to separate but that is a different bug.
